ccflags-y := -O3 -ffast-math $(call cc-option,-fgcse-lm) $(call cc-option,-fgcse-sm) $(call cc-option,-fsched-spec-load) $(call cc-option,-fforce-addr) $(call cc-option,-fsingle-precision-constant) -mcpu=cortex-a15 -mtune=cortex-a15 -marm -mfpu=neon-vfpv4
obj-y += msm_ion.o ion_cp_common.o ion_iommu_map.o
